### PR TITLE
Fetch latest template changes & update source.

### PR DESCRIPTION
**Pull request by nickpellant**

### CODE REVIEW

**Comment by MoOx** [comment]
Can you just squash all those commits ?

**Comment by nickpellant** [comment]
@MoOx I'm having some issues getting the commits to squash correctly... any advice?

**Comment by MoOx** [comment]
No sorry, I'm not a squash pro :/

**Comment by MoOx** [comment]
Maybe check squash with rebase.

**Comment by nickpellant** [comment]
Darn nor me! I have done an interactive rebase to squash commits but getting a whole host of conflicts.

**Comment by jacobbednarz** [comment]
Deprecated in favour of [brewcask][1] and [Boxen's in built support for
homebrew/brewcask][2].

[1]: https://caskroom.github.io/
[2]: https://github.com/boxen/puppet-boxen/blob/master/manifests/personal.pp#L14-L17

**Pull request closed without merging**
